import { test, expect } from "bun:test";
import { hashContext } from "@nexsidi/context-chain";
import { filterSourceManifest } from "./index.ts";

// Root cause (live, project=simple1, 2026-07-26): runQAFixLoopActivity
// records the context-chain handoff hash right after QA passes; the
// workflow then runs a SECOND post-QA runCompileCheck (tsc --noEmit)
// before runDeployWithLiveRetest re-hashes the same manifest to verify
// it. When a generated frontend's tsconfig.json has "incremental": true
// (Next.js's own default), tsc writes/touches a tsconfig.tsbuildinfo file
// at the project root during that post-QA compile check — a file that
// didn't exist (or had different content) at record time. filesWritten
// picks it up, the two hashes diverge, and Patent Claim 3's rollback
// fires on a false positive: the actual generated SOURCE never changed.

const stage4Result = {
  backendOutputDir: "/tmp/nexsidi-builds/p1/backend",
  frontendOutputDir: "/tmp/nexsidi-builds/p1/frontend",
  filesWritten: ["frontend/app/page.tsx", "frontend/package.json"],
};

test("filterSourceManifest excludes node_modules, .next, and dist (existing behavior)", () => {
  const result = filterSourceManifest({
    ...stage4Result,
    filesWritten: [
      "frontend/app/page.tsx",
      "frontend/node_modules/react/index.js",
      "frontend/.next/cache/foo.pack",
      "backend/dist/index.js",
    ],
  });
  expect(result.filesWritten).toEqual(["frontend/app/page.tsx"]);
});

// Real root cause of the live verify361300 rollback (2026-08-05): Riya's
// deploy step runs `git init && git add -A && git commit` (agents/riya/src/
// index.ts) as the normal "GitHub repo" deliverable. buildStage4Result does
// a LIVE rescan of the build dir on every call, so when stage6's own retry
// re-invokes verifyHandoff after Riya's FIRST attempt already ran git init,
// the rescan sees .git/* files that weren't present at record time — a
// false-positive mismatch against the pipeline's own artifact, not tampering.
test("filterSourceManifest excludes .git files created by Riya's own git init/commit deploy step", () => {
  const before = filterSourceManifest(stage4Result);
  const after = filterSourceManifest({
    ...stage4Result,
    filesWritten: [
      ...stage4Result.filesWritten,
      ".git/COMMIT_EDITMSG",
      ".git/HEAD",
      ".git/config",
      ".git/hooks/applypatch-msg.sample",
      ".git/refs/heads/main",
    ],
  });
  expect(after.filesWritten).toEqual(before.filesWritten);
});

test("filterSourceManifest excludes a tsconfig.tsbuildinfo file written by a post-QA tsc --noEmit run", () => {
  const before = filterSourceManifest(stage4Result);
  const after = filterSourceManifest({
    ...stage4Result,
    filesWritten: [...stage4Result.filesWritten, "frontend/tsconfig.tsbuildinfo"],
  });
  expect(after.filesWritten).toEqual(before.filesWritten);
});

// Real root cause of the live simple1 rollback (confirmed by mtime forensics:
// no file in the build dir changed at all between recordHandoff and the
// rollback firing minutes later — so the drift was never about file lists).
// filterSourceManifest's return value is hashed as-is by recordHandoff/
// verifyHandoff. It carries the two RAW ABSOLUTE build-dir paths through
// unchanged — paths that depend on how BUILD_DIR got resolved in whichever
// process ran (drive-letter case, forward vs back slashes, trailing slash,
// whether .env was loaded via --env-file or Bun's auto-loader). None of that
// reflects the generated SOURCE QA actually reviewed, so it must never
// affect the hash Claim 3 uses to detect real tampering.
test("filterSourceManifest's hashed output is identical across differently-formatted (but equivalent) absolute build-dir paths", () => {
  const a = filterSourceManifest({
    backendOutputDir: "C:/tmp/nexsidi-builds/simple1/backend",
    frontendOutputDir: "C:/tmp/nexsidi-builds/simple1/frontend",
    filesWritten: stage4Result.filesWritten,
  });
  const b = filterSourceManifest({
    backendOutputDir: "C:\\tmp\\nexsidi-builds\\simple1\\backend",
    frontendOutputDir: "c:\\tmp\\nexsidi-builds\\simple1\\frontend\\",
    filesWritten: stage4Result.filesWritten,
  });
  expect(hashContext(a)).toBe(hashContext(b));
});

// Second confirmed instance of the same class of bug (live, simple1,
// 2026-07-26): backend/package-lock.json's mtime landed inside the exact
// window between recordHandoff (end of Stage 5) and the rollback fired by
// verifyHandoff (Stage 6) — the post-QA runCompileCheck's `bun install`
// step rewrites the lockfile as a side effect of installing deps for tsc,
// even when package.json (the actual agent-authored source) is unchanged.
test("filterSourceManifest excludes lockfiles regenerated by a post-QA dependency install", () => {
  const before = filterSourceManifest(stage4Result);
  const after = filterSourceManifest({
    ...stage4Result,
    filesWritten: [
      ...stage4Result.filesWritten,
      "backend/package-lock.json",
      "frontend/bun.lock",
      "backend/bun.lockb",
      "frontend/yarn.lock",
      "backend/pnpm-lock.yaml",
    ],
  });
  expect(after.filesWritten).toEqual(before.filesWritten);
});
