// Clone an existing delivered project into a new one with a name/branding
// swap — a deterministic, non-LLM v1 of the "clone flow" (2026-09-01, real
// user request): copy the already-generated, already-QA-passed code
// wholesale instead of paying for a fresh spec → generate → adversarial QA →
// two Tilotma review passes run every time. Scoped intentionally: this
// swaps the literal display name/branding text via find-and-replace, not
// deeper content variation (different testimonials, different colors) —
// that needs an LLM-assisted pass and is a natural v2, not built here.
import { existsSync, mkdirSync, readdirSync, statSync, readFileSync, writeFileSync, cpSync } from "node:fs";
import { join } from "node:path";
import { findFreePort, isPortUsedByDocker } from "../../agents/riya/src/index.ts";
import { applyThemeVariation, type ApplyThemeVariationResult } from "./clone-theme.ts";

// Never copy these — regenerated by the Dockerfile's own install/build
// steps, and .next/.git are either huge derived output or VCS-specific
// (a fresh project needs its own git history, not the source's).
const SKIP_COPY_DIRS = new Set(["node_modules", ".next", ".git", "dist", "tsconfig.tsbuildinfo"]);

// Text file extensions worth scanning for the name swap — binary assets
// (images, the logo data URI lives inline in .tsx so that's covered) don't
// need it and scanning them would be wasted work.
const TEXT_FILE_EXTENSIONS = new Set([".ts", ".tsx", ".json", ".yml", ".yaml", ".css", ".md", ".txt"]);

function copyProjectDir(sourceDir: string, destDir: string): void {
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(sourceDir)) {
    if (SKIP_COPY_DIRS.has(entry)) continue;
    const srcPath = join(sourceDir, entry);
    const destPath = join(destDir, entry);
    const stat = statSync(srcPath);
    if (stat.isDirectory()) {
      copyProjectDir(srcPath, destPath); // recurse, applying the same skip-list at every level
    } else {
      cpSync(srcPath, destPath);
    }
  }
}

// Walks the copied tree and replaces every literal occurrence of oldName
// with newName in text files. Exported so the exact substitution logic is
// independently testable without needing a real directory copy.
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function renameInFile(content: string, oldName: string, newName: string): string {
  // Escape regex metacharacters in oldName — a company name like "R&D Co."
  // or "C++ Labs" must be matched literally, not interpreted as a pattern.
  let result = content.replace(new RegExp(escapeRegex(oldName), "g"), newName);

  // 2026-09-02: real bug found live cloning Gatherly — its own Navbar hardcodes
  // the wordmark as a literal ALL-CAPS string ("GATHERLY") rather than computing
  // it from the name via text-transform/toUpperCase, so the exact-case pass
  // above never touches it and the OLD company name stays visibly in the nav
  // after a clone. Only runs when the uppercase form actually differs from the
  // exact-case form already handled — skips redundant work for a name that was
  // already all-caps to begin with.
  const oldUpper = oldName.toUpperCase();
  if (oldUpper !== oldName) {
    result = result.replace(new RegExp(escapeRegex(oldUpper), "g"), newName.toUpperCase());
  }

  return result;
}

function renameInDir(dir: string, oldName: string, newName: string): void {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      renameInDir(full, oldName, newName);
      continue;
    }
    const dotIdx = entry.lastIndexOf(".");
    const ext = dotIdx === -1 ? "" : entry.slice(dotIdx);
    if (!TEXT_FILE_EXTENSIONS.has(ext)) continue;
    const content = readFileSync(full, "utf-8");
    const renamed = renameInFile(content, oldName, newName);
    if (renamed !== content) writeFileSync(full, renamed, "utf-8");
  }
}

export interface ClonePorts {
  frontendPort: number;
  backendPort: number;
  dbPort: number;
}

// Reads the CONFIGURED ports straight from compose file text — deliberately
// does not require the containers to actually be running (unlike Riya's
// getRunningDeploymentPorts, which docker-verifies on purpose for deploy
// decisions). Cloning a currently-stopped project is a completely normal
// case; the source's ports still need to be known to compute fresh ones.
// Same block-bounded regex as getRunningDeploymentPorts (see that
// function's own comment for why "next 2-space-indented line" and not a
// looser match) — kept as an independent copy rather than a shared import
// since the two functions have different verification guarantees and
// should stay easy to reason about separately.
export function parseComposePorts(compose: string): ClonePorts | null {
  const portFor = (service: string): number | null => {
    const blockMatch = compose.match(new RegExp(`\\n  ${service}:\\n([\\s\\S]*?)(?=\\n {2}\\S|$)`));
    const captured = blockMatch?.[1];
    if (!captured) return null;
    const m = captured.match(/-\s*"(\d+):\d+"/);
    return m ? Number(m[1]) : null;
  };
  const frontendPort = portFor("frontend");
  const backendPort = portFor("backend");
  const dbPort = portFor("postgres");
  if (frontendPort === null || backendPort === null || dbPort === null) return null;
  return { frontendPort, backendPort, dbPort };
}

// Rewrites the 3 host ports in a copied docker-compose.yml (frontend,
// backend, postgres) plus every reference to the OLD backend port in
// NEXT_PUBLIC_API_URL/CORS_ORIGIN — the same class of bug tonight's real
// port-collision cleanup found and fixed by hand across 3 existing
// projects; a clone must never be born already colliding with its source.
// Exported and pure (string in, string out) so the rewrite itself is
// directly testable without a real compose file on disk.
export function rewriteComposePorts(compose: string, oldPorts: ClonePorts, newPorts: ClonePorts): string {
  // 2026-09-01: real bug caught by this function's own test — sequential
  // direct old->new replacements corrupt each other whenever a NEW port
  // happens to numerically equal a DIFFERENT service's OLD port (e.g. the
  // new frontend port lands on the old backend port's number): the second
  // replacement pass matches text the FIRST pass just wrote, not just the
  // original source. Two-phase placeholder swap (old->unique token, THEN
  // token->new) guarantees no intermediate state can ever collide with any
  // real port number, old or new.
  const FRONTEND_TOKEN = "__NEXSIDI_CLONE_FRONTEND_PORT__";
  const BACKEND_TOKEN = "__NEXSIDI_CLONE_BACKEND_PORT__";
  const DB_TOKEN = "__NEXSIDI_CLONE_DB_PORT__";

  let out = compose;
  out = out.replace(new RegExp(`"${oldPorts.frontendPort}:`, "g"), `"${FRONTEND_TOKEN}:`);
  out = out.replace(new RegExp(`"${oldPorts.backendPort}:`, "g"), `"${BACKEND_TOKEN}:`);
  out = out.replace(new RegExp(`"${oldPorts.dbPort}:`, "g"), `"${DB_TOKEN}:`);
  out = out.replace(new RegExp(`localhost:${oldPorts.backendPort}\\b`, "g"), `localhost:${BACKEND_TOKEN}`);
  out = out.replace(new RegExp(`localhost:${oldPorts.frontendPort}\\b`, "g"), `localhost:${FRONTEND_TOKEN}`);

  out = out.replaceAll(FRONTEND_TOKEN, String(newPorts.frontendPort));
  out = out.replaceAll(BACKEND_TOKEN, String(newPorts.backendPort));
  out = out.replaceAll(DB_TOKEN, String(newPorts.dbPort));
  return out;
}

export interface CloneProjectOptions {
  sourceProjectId: string;
  newProjectId: string;
  oldName: string;
  newName: string;
  sourcePorts: ClonePorts;
  buildDir?: string;
}

export interface CloneProjectResult {
  newProjectId: string;
  buildDir: string;
  ports: ClonePorts;
  theme: ApplyThemeVariationResult;
}

export async function cloneProject(
  opts: CloneProjectOptions,
  deps: { findFreePort?: typeof findFreePort; isPortUsedByDocker?: typeof isPortUsedByDocker } = {},
): Promise<CloneProjectResult> {
  const findPort = deps.findFreePort ?? findFreePort;
  const baseDir = opts.buildDir ?? process.env.BUILD_DIR ?? "E:/tmp/nexsidi-builds";
  const sourceDir = join(baseDir, opts.sourceProjectId);
  const destDir = join(baseDir, opts.newProjectId);

  if (!existsSync(sourceDir)) throw new Error(`clone source not found: ${sourceDir}`);
  if (existsSync(destDir)) throw new Error(`clone destination already exists: ${destDir} — refusing to overwrite`);

  copyProjectDir(sourceDir, destDir);

  // Fresh, collision-free ports — same ranges tonight's manual port
  // reassignment used (32xx frontend, 33xx backend, 54xx db), scanning
  // forward from just past the source's own ports as a reasonable start
  // point rather than always restarting the search from the very bottom.
  const frontendPort = await findPort(opts.sourcePorts.frontendPort + 1, 3299);
  const backendPort = await findPort(opts.sourcePorts.backendPort + 1, 3399);
  const dbPort = await findPort(opts.sourcePorts.dbPort + 1, 5499);
  const newPorts: ClonePorts = { frontendPort, backendPort, dbPort };

  renameInDir(destDir, opts.oldName, opts.newName);

  // Always runs — not gated behind an LLM `changes` request. Two clones
  // that only differ by name would still visibly read as the same
  // template when shown side by side; this is the mechanical fix for that,
  // so it costs zero LLM tokens and never depends on the optional edit
  // pass. Seeded on the new project's own id, so it's deterministic and
  // different clones from the same source land on different accents too.
  const theme = applyThemeVariation(destDir, opts.newProjectId);

  const composePath = join(destDir, "docker-compose.yml");
  if (existsSync(composePath)) {
    const compose = readFileSync(composePath, "utf-8");
    writeFileSync(composePath, rewriteComposePorts(compose, opts.sourcePorts, newPorts), "utf-8");
  }

  // spec.json's own projectId/name fields — the rename pass above only
  // touches the display name text, not these structured identity fields.
  const specPath = join(destDir, "spec.json");
  if (existsSync(specPath)) {
    const spec = JSON.parse(readFileSync(specPath, "utf-8"));
    spec.projectId = opts.newProjectId;
    spec.name = opts.newName;
    writeFileSync(specPath, JSON.stringify(spec, null, 2), "utf-8");
  }

  return { newProjectId: opts.newProjectId, buildDir: destDir, ports: newPorts, theme };
}
